/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import DomainModels.NhaCC;
import Services.Impl.NhaCCService;
import Utilities.DBConnection;
import Utilities.SetSize;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class FrmNhaCungCap extends javax.swing.JFrame {
    final SetSize setsize = new SetSize();
    final static NhaCCService SERVICE = new NhaCCService();
    static NhaCC NHACC_DUOCCHON;
    static{
        if(!SERVICE.getAll().isEmpty()){
            NHACC_DUOCCHON = SERVICE.getAll().get(0);
        }
    }
    /**
     * Creates new form FrmNhaCungCap
     */
    public FrmNhaCungCap() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        this.seticon();
        this.fillCBX();
          ButtonGroup buttonGroup = new ButtonGroup();
        buttonGroup.add(rdsua);
        buttonGroup.add(rdxoa);
        buttonGroup.add(rdthem);
        rdthem.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtten = new javax.swing.JTextField();
        txtdiachi = new javax.swing.JTextField();
        btnHoanThanh = new javax.swing.JButton();
        btnClose = new javax.swing.JLabel();
        cbxNhaCC = new javax.swing.JComboBox<>();
        rdthem = new javax.swing.JRadioButton();
        rdsua = new javax.swing.JRadioButton();
        rdxoa = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtsdt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nhà cung cấp");

        jLabel2.setText("Tên");

        jLabel3.setText("Địa chỉ");

        btnHoanThanh.setBackground(new java.awt.Color(125, 200, 150));
        btnHoanThanh.setText("Hoàn thành");
        btnHoanThanh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHoanThanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoanThanhActionPerformed(evt);
            }
        });

        btnClose.setPreferredSize(new java.awt.Dimension(20, 20));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        cbxNhaCC.setBackground(new java.awt.Color(125, 200, 150));
        cbxNhaCC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxNhaCC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxNhaCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxNhaCCMouseClicked(evt);
            }
        });

        rdthem.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdthem);
        rdthem.setText("Thêm");

        rdsua.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdsua);
        rdsua.setText("Sửa");

        rdxoa.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdxoa);
        rdxoa.setText("Xóa");

        jLabel5.setText("SDT");

        jLabel6.setText("Email");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 34, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnHoanThanh)
                                .addGap(122, 122, 122))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(cbxNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdthem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rdsua)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rdxoa))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtten)
                                            .addComponent(txtdiachi)
                                            .addComponent(txtsdt)
                                            .addComponent(txtemail, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))))
                                .addGap(36, 36, 36))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdthem)
                    .addComponent(rdsua)
                    .addComponent(rdxoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHoanThanh)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnHoanThanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoanThanhActionPerformed
        // TODO add your handling code here:
                String str = txtsdt.getText();
        String str1 = txtemail.getText();
        String reg = "^(0|\\+84)(\\s|\\.)?((3[2-9])|(5[689])|(7[06-9])|(8[1-689])|(9[0-46-9]))(\\d)(\\s|\\.)?(\\d{3})(\\s|\\.)?(\\d{3})$";
        String regemail = "^(?=.{1,64}@)[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$";
        boolean kt = str.matches(reg);
        boolean kt1 = str1.matches(regemail);

        if (rdthem.isSelected() == true) {
            NhaCC nhacc = new NhaCC();
            try {
                if (txtten.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Không được để trống tên");
                } else if (txtdiachi.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Không được để trống Địa Chỉ");
                } else if (txtsdt.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Không được để trống SĐT");
                } else if (kt == false) {
                    JOptionPane.showMessageDialog(this, "Không Đúng định dạng của sđt");
                } else if (txtemail.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Không được để trống Email");
                } else if (kt1 == false) {
                    JOptionPane.showMessageDialog(this, "Không đúng định dạng  Email");
                } else {
                    try {
                        ResultSet rs = DBConnection.getDataFromQuery("SELECT Count(*) as TenNhaCC from NhaCC where TenNhaCC = ?", txtten.getText());
                        NhaCC cv = new NhaCC();
                        while (rs.next()) {
                            if (rs.getInt("TenNhaCC") != 0) {
                                JOptionPane.showMessageDialog(this, "ĐÃ có nhà cung cấp này rồi");
                            }else{
                            cv = new NhaCC(null, txtten.getText(),
                                   txtdiachi.getText(), txtsdt.getText(), txtemail.getText());
                            SERVICE.Them(cv);
                            JOptionPane.showMessageDialog(this, "Thêm Thành công");
                            fillCBX();
                            
                            }
                        }

                    } catch (SQLException ex) {
                        ex.printStackTrace();

                    }
                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        } else if (rdsua.isSelected() == true) {
            NhaCC nhacc = new NhaCC();
            try {
                nhacc = new NhaCC(cbxNhaCC.getActionCommand(), txtten.getText(), txtdiachi.getText(), txtsdt.getText(), txtemail.getText());
                SERVICE.Sua(nhacc);
                JOptionPane.showMessageDialog(this, "Sửa Thành Công");
                fillCBX();
            } catch (Exception e) {
            }

        } else if (rdxoa.isSelected() == true) {
            String ten = txtten.getText();
            SERVICE.xoa(ten);
            JOptionPane.showMessageDialog(this, "Xóa Thành công");
            txtten.setText("");
            txtdiachi.setText("");
            txtemail.setText("");
            txtsdt.setText("");
            fillCBX();
        }
        FrmPhieuNhap.fillCbxNCC();
        int index = this.cbxNhaCC.getSelectedIndex();
        System.out.println(index);
        FrmPhieuNhap.cbxNCC.setSelectedIndex(index);
        NHACC_DUOCCHON = SERVICE.getAll().get(index);
        System.out.println(NHACC_DUOCCHON.getId());
        this.dispose();
    }//GEN-LAST:event_btnHoanThanhActionPerformed

    private void cbxNhaCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxNhaCCMouseClicked
        // TODO add your handling code here:
        filltxt();
    }//GEN-LAST:event_cbxNhaCCMouseClicked

    private void seticon(){
        URL urldong = getClass().getResource("/Images/cross-small.png");
        btnClose.setIcon(setsize.setSizeAnh(urldong, 20, 20));
    }

    private void fillCBX(){
        List<NhaCC> _lst = SERVICE.getAll();
        cbxNhaCC.removeAllItems();
        for (NhaCC nhaCC : _lst) {
            cbxNhaCC.addItem(nhaCC.getTen());
        }
    }
    
      public void filltxt() {
        try {
            String cb = cbxNhaCC.getSelectedItem().toString();
            txtten.setText(cb);
        } catch (NullPointerException e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private javax.swing.JButton btnHoanThanh;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxNhaCC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rdsua;
    private javax.swing.JRadioButton rdthem;
    private javax.swing.JRadioButton rdxoa;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txtten;
    // End of variables declaration//GEN-END:variables
}
