/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import DomainModels.NhaCC;
import DomainModels.NhaXuatBan;
import DomainModels.PhieuNhap;
import DomainModels.Sach;
import DomainModels.SachCT;
import DomainModels.TacGia;
import DomainModels.TheLoaiSach;
import Services.Impl.NhaCCService;
import Services.Impl.NhaXuatBanService;
import Services.Impl.PhieuNhapService;
import Services.Impl.SachCTService;
import Services.Impl.SachService;
import Services.Impl.TacGiaService;
import Services.Impl.TheLoaiService;
import Utilities.SetSize;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.math.BigDecimal;
import java.net.URL;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author Admin
 */
public class FrmPhieuNhap extends javax.swing.JFrame {
    final SetSize setsize = new SetSize();
    final PhieuNhapService SERVICE = new PhieuNhapService();
    final SachService SERVICE_SACH = new SachService();
    final SachCTService SERVICE_SACHCT = new SachCTService();
    final TheLoaiService SERVICE_TLS = new TheLoaiService();
    final TacGiaService SERVICE_TG = new TacGiaService();
    static int ipn =20000;
    static int isach = 20000;
    static int suaAnh = 0;
    static String icon = "";
    final SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    /**
     * Creates new form NewJFrame
     */
    public FrmPhieuNhap() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        this.seticon();
        fillCbxNXB();
        fillCbxNCC();
        fillChkTL();
        this.setNgayNhap();
    }

    private void seticon(){
        URL urldong = getClass().getResource("/Images/cross-small.png");
        btnDong.setIcon(setsize.setSizeAnh(urldong, 20, 20));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblToday = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rdoDaCo = new javax.swing.JRadioButton();
        rdoChuaCo = new javax.swing.JRadioButton();
        btnDong = new javax.swing.JLabel();
        PnThongTinSach = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaSach = new javax.swing.JTextField();
        btnLayThongTin = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtTenSach = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSoLuongNhap = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        boxTheLoai = new javax.swing.JPanel();
        Btn = new javax.swing.JPanel();
        btnTheLoai = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        txtNamXuatBan = new javax.swing.JTextField();
        btnHoanThanh = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        imgAnhSach = new javax.swing.JLabel();
        btnTaiAnh = new javax.swing.JButton();
        btnNXB = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        cbxNCC = new javax.swing.JComboBox<>();
        btnNhaCungCap = new javax.swing.JButton();
        btnTacGia = new javax.swing.JButton();
        lblTacGia = new javax.swing.JLabel();
        cbxNhaXuatBan = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 200, 150)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Phiếu nhập");

        lblToday.setText("14:09, 10-11-2022");

        jLabel4.setText("ID:");

        jLabel5.setText("IS ID");

        jLabel6.setText("Tình trạng:");

        rdoDaCo.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoDaCo);
        rdoDaCo.setText("Đã có");
        rdoDaCo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdoDaCo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdoDaCoMouseClicked(evt);
            }
        });

        rdoChuaCo.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoChuaCo);
        rdoChuaCo.setText("Chưa có");
        rdoChuaCo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdoChuaCo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdoChuaCoMouseClicked(evt);
            }
        });

        btnDong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDong.setPreferredSize(new java.awt.Dimension(22, 22));
        btnDong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDongMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(246, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(214, 214, 214)
                .addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblToday)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rdoDaCo)
                                .addGap(18, 18, 18)
                                .addComponent(rdoChuaCo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblToday, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rdoDaCo)
                    .addComponent(rdoChuaCo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 110));

        PnThongTinSach.setBackground(new java.awt.Color(255, 255, 255));
        PnThongTinSach.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 200, 150)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Thông tin sách nhập");

        jLabel7.setText("Mã sách");

        txtMaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSachActionPerformed(evt);
            }
        });

        btnLayThongTin.setBackground(new java.awt.Color(125, 200, 150));
        btnLayThongTin.setText("Check");
        btnLayThongTin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel8.setText("Tên sách");

        jLabel9.setText("Tác giả");

        jLabel10.setText("Số lượng");

        jLabel11.setText("Nhà xuất bản");

        jLabel12.setText("Thể loại");

        jLabel13.setText("Năm xuất bản");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        boxTheLoai.setBackground(new java.awt.Color(255, 255, 255));
        boxTheLoai.setMaximumSize(new java.awt.Dimension(185, 900));
        boxTheLoai.setMinimumSize(new java.awt.Dimension(185, 30));
        boxTheLoai.setPreferredSize(new java.awt.Dimension(185, 100));
        boxTheLoai.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        Btn.setBackground(new java.awt.Color(255, 255, 255));
        Btn.setPreferredSize(new java.awt.Dimension(250, 24));
        Btn.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        btnTheLoai.setBackground(new java.awt.Color(125, 200, 150));
        btnTheLoai.setText("Khác");
        btnTheLoai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTheLoaiActionPerformed(evt);
            }
        });
        Btn.add(btnTheLoai);

        boxTheLoai.add(Btn);

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Tâm lý");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        boxTheLoai.add(jCheckBox1);

        jCheckBox2.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Khoa học-viễn tưởng");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        boxTheLoai.add(jCheckBox2);

        jCheckBox3.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setText("Tình cảm");
        boxTheLoai.add(jCheckBox3);

        jCheckBox4.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setText("Kinh doanh - kinh tế");
        boxTheLoai.add(jCheckBox4);

        jScrollPane1.setViewportView(boxTheLoai);

        btnHoanThanh.setBackground(new java.awt.Color(125, 200, 150));
        btnHoanThanh.setText("Hoàn thành");
        btnHoanThanh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHoanThanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoanThanhActionPerformed(evt);
            }
        });

        jLabel15.setText("Giá nhập");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgAnhSach, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgAnhSach, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
        );

        btnTaiAnh.setBackground(new java.awt.Color(125, 200, 150));
        btnTaiAnh.setText("Tải ảnh");
        btnTaiAnh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTaiAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiAnhActionPerformed(evt);
            }
        });

        btnNXB.setBackground(new java.awt.Color(125, 200, 150));
        btnNXB.setText("Khác");
        btnNXB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNXBActionPerformed(evt);
            }
        });

        jLabel14.setText("Nhà cung cấp");

        cbxNCC.setBackground(new java.awt.Color(125, 200, 150));
        cbxNCC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxNCC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNCCActionPerformed(evt);
            }
        });

        btnNhaCungCap.setBackground(new java.awt.Color(125, 200, 150));
        btnNhaCungCap.setText("Khác");
        btnNhaCungCap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhaCungCapActionPerformed(evt);
            }
        });

        btnTacGia.setBackground(new java.awt.Color(125, 200, 150));
        btnTacGia.setText("Chọn");
        btnTacGia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTacGiaActionPerformed(evt);
            }
        });

        lblTacGia.setText("-----");

        cbxNhaXuatBan.setBackground(new java.awt.Color(125, 200, 150));
        cbxNhaXuatBan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxNhaXuatBan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxNhaXuatBanItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout PnThongTinSachLayout = new javax.swing.GroupLayout(PnThongTinSach);
        PnThongTinSach.setLayout(PnThongTinSachLayout);
        PnThongTinSachLayout.setHorizontalGroup(
            PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnThongTinSachLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(PnThongTinSachLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PnThongTinSachLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PnThongTinSachLayout.createSequentialGroup()
                                    .addComponent(txtSoLuongNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(cbxNhaXuatBan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTacGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNXB)
                    .addComponent(btnTacGia)
                    .addComponent(btnNhaCungCap)
                    .addComponent(btnLayThongTin))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(PnThongTinSachLayout.createSequentialGroup()
                .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnThongTinSachLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2))
                    .addGroup(PnThongTinSachLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnTaiAnh)
                        .addGap(33, 33, 33)
                        .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnThongTinSachLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHoanThanh)))
                            .addGroup(PnThongTinSachLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNamXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnThongTinSachLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PnThongTinSachLayout.setVerticalGroup(
            PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnThongTinSachLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(21, 21, 21)
                .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PnThongTinSachLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(15, 15, 15)
                        .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lblTacGia))
                        .addGap(25, 25, 25)
                        .addComponent(jLabel10)
                        .addGap(15, 15, 15)
                        .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(btnNXB)
                            .addComponent(cbxNhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PnThongTinSachLayout.createSequentialGroup()
                        .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLayThongTin))
                        .addGap(12, 12, 12)
                        .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnTacGia)
                        .addGap(16, 16, 16)
                        .addComponent(txtSoLuongNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTaiAnh)
                    .addGroup(PnThongTinSachLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(13, 13, 13)
                .addGroup(PnThongTinSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNhaCungCap)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnHoanThanh)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel1.add(PnThongTinSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 112, 580, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdoDaCoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdoDaCoMouseClicked
        // TODO add your handling code here:
        this.checkSach(false);
    }//GEN-LAST:event_rdoDaCoMouseClicked

    private void rdoChuaCoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdoChuaCoMouseClicked
        // TODO add your handling code here:
        this.checkSach(true);
        txtMaSach.setText("is auto");
        txtMaSach.setEditable(false);
    }//GEN-LAST:event_rdoChuaCoMouseClicked

    private void btnDongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDongMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnDongMouseClicked

    private void txtMaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSachActionPerformed

    private void btnNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNXBActionPerformed
        // TODO add your handling code here:
        FrmNhaXuatBan nxb = new FrmNhaXuatBan();
        nxb.setVisible(true);
    }//GEN-LAST:event_btnNXBActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void btnNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhaCungCapActionPerformed
        // TODO add your handling code here:
        FrmNhaCungCap nhaCungCap = new FrmNhaCungCap();
        nhaCungCap.setVisible(true);
    }//GEN-LAST:event_btnNhaCungCapActionPerformed

    private void btnTheLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTheLoaiActionPerformed
        // TODO add your handling code here:
        FrmTheLoai theLoai = new FrmTheLoai();
        theLoai.setVisible(true);
    }//GEN-LAST:event_btnTheLoaiActionPerformed

    private void btnTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTacGiaActionPerformed
        // TODO add your handling code here:
        FrmTacGia tacGia = new FrmTacGia();
        tacGia.setVisible(true);
    }//GEN-LAST:event_btnTacGiaActionPerformed

    private void cbxNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNCCActionPerformed
        // TODO add your handling code here:
        rdoChuaCo.setSelected(true);
        this.checkSach(true);
    }//GEN-LAST:event_cbxNCCActionPerformed

    private void cbxNhaXuatBanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxNhaXuatBanItemStateChanged
        // TODO add your handling code here:\
        rdoChuaCo.setSelected(true);
        this.checkSach(true);
    }//GEN-LAST:event_cbxNhaXuatBanItemStateChanged

    private void btnHoanThanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoanThanhActionPerformed
        // TODO add your handling code here:
        Sach sach = getSachFormData();
        SERVICE_SACH.insert(sach);
        Sach sachNew = SERVICE_SACH.getByMa(sach.getMa());
        List<TacGia>_lstTacGia = FrmTacGia.LST_TACGIA_DUOCCHON;
        for (TacGia tacGia : _lstTacGia) {
            SERVICE_TG.insertTGCT(sachNew.getId(), tacGia.getId());
        }
        List<TheLoaiSach> _lstTLS = getListTheLoai();
        for (TheLoaiSach theLoaiSach : _lstTLS) {
            SERVICE_TLS.insertTLCT(sachNew.getId(), theLoaiSach.getId());
        }
        SachCT sachct = getSachCTFormData(sachNew);
        SERVICE_SACHCT.insert(sachct);
        PhieuNhap pn = getPhieuNhapFormData();
        SERVICE.insert(pn);
        NhaCC nhaCC = FrmNhaCungCap.NHACC_DUOCCHON;
        SERVICE.InsertNCCCT(SERVICE.getByMa(pn.getMa()).getId(), nhaCC.getId());
        this.dispose();
    }//GEN-LAST:event_btnHoanThanhActionPerformed

    private void btnTaiAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiAnhActionPerformed
        // TODO add your handling code here:
        suaAnh=1;
        JFileChooser choose = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        choose.showDialog(this, "Confirm");
        File file = choose.getSelectedFile();
        icon = file.getAbsolutePath();
        ImageIcon img = new ImageIcon(icon);
        Image imgset = img.getImage();
        ImageIcon imgm = new ImageIcon(imgset.getScaledInstance(133, 162, java.awt.Image.SCALE_SMOOTH));
        imgAnhSach.setIcon(imgm);
    }//GEN-LAST:event_btnTaiAnhActionPerformed

    public void checkSach(boolean ft){
        txtMaSach.setText("");
        txtMaSach.setEditable(!ft);
        txtTenSach.setEditable(ft);
        txtNamXuatBan.setEditable(ft);
        txtDonGia.setEditable(ft);
        btnTaiAnh.setEnabled(ft);
    }

    public void xemChiTiet(){
        PnThongTinSach.remove(btnLayThongTin);
        PnThongTinSach.remove(btnTacGia);
        PnThongTinSach.remove(btnTaiAnh);
        PnThongTinSach.remove(btnNXB);
        PnThongTinSach.remove(btnNhaCungCap);
        PnThongTinSach.remove(btnHoanThanh);
        PnThongTinSach.remove(btnTaiAnh);
        txtMaSach.setEditable(false);
        txtNamXuatBan.setEditable(false);
        txtSoLuongNhap.setEditable(false);
    }

    public static void fillCbxNXB(){
        NhaXuatBanService service = new NhaXuatBanService();
        List<NhaXuatBan>  _lst = service.getAll();
        cbxNhaXuatBan.removeAllItems();
        for (NhaXuatBan nhaXuatBan : _lst) {
            cbxNhaXuatBan.addItem(nhaXuatBan.getTen());
        }
    }

    public static void fillCbxNCC(){
        NhaCCService service = new NhaCCService();
        List<NhaCC>  _lst = service.getAll();
        cbxNCC.removeAllItems();
        for (NhaCC nhaCC : _lst) {
            cbxNCC.addItem(nhaCC.getTen());
        }
    }

    public static void fillChkTL(){
        TheLoaiService service = new TheLoaiService();
        JComponent btn = (JComponent) boxTheLoai.getComponent(0);
        List<TheLoaiSach> _lst = service.getAll();
        boxTheLoai.removeAll();
        boxTheLoai.add(btn);
        for (TheLoaiSach theLoaiSach : _lst) {
            JCheckBox chk = new JCheckBox(theLoaiSach.getTen());
            chk.setBackground(Color.white);
            boxTheLoai.add(chk);
        }
    }
    
    private String roleMaPhieuNhap(){
        List<PhieuNhap> _lst = SERVICE.getAll();
        if(!_lst.isEmpty()){
            for (PhieuNhap phieuNhap : _lst) {
                String maphieu = phieuNhap.getMa();
                int max = Integer.parseInt(maphieu.substring(2));
                if(ipn<max){
                    ipn=max;
                }
            }
        }
        ipn++;
        String ma = "PN"+ipn;
        return ma;
        
    }
    
    private String roleMaSach(){
        List<Sach> _lst = SERVICE_SACH.getAll();
        if(!_lst.isEmpty()){
            for (Sach sach : _lst) {
                String maphieu = sach.getMa();
                int max = Integer.parseInt(maphieu.substring(2));
                if(isach<max){
                    isach=max;
                }
            }
        }
        isach++;
        String ma = "MS"+isach;
        return ma;
    }
    
    private void setNgayNhap(){
        Calendar c = Calendar.getInstance();
        int ngay = c.get(Calendar.DATE);
        int Thang = c.get(Calendar.MONTH);
        int nam = c.get(Calendar.YEAR);
        String date = ngay+"-"+Thang+"-"+nam;
        lblToday.setText(date);
    }
    
    private PhieuNhap getPhieuNhapFormData(){
        String ma = roleMaPhieuNhap();
        String ngayNhap = lblToday.getText();
        Boolean tinhTrang = rdoDaCo.isSelected();
        int soLuongNhap = Integer.parseInt(txtSoLuongNhap.getText());
        Double giaNhap = Double.valueOf(txtDonGia.getText());
        BigDecimal giaNhapChuan = BigDecimal.valueOf(giaNhap);
        try {
            return new PhieuNhap(null, ma, null, sdf.parse(ngayNhap), tinhTrang, soLuongNhap, giaNhapChuan);
        } catch (ParseException ex) {
            ex.printStackTrace();
            return null;
        }
    }
    
    private Sach getSachFormData(){
        String ma = roleMaSach();
        String ten = txtTenSach.getText();
        return new Sach(null, ma, ten);
    }
    
    private SachCT getSachCTFormData(Sach sach){
        int namXB = Integer.parseInt(txtNamXuatBan.getText());
        Double giaNhap = Double.valueOf(txtDonGia.getText());
        BigDecimal giaNhapChuan = BigDecimal.valueOf(giaNhap);
        NhaXuatBan nxb = FrmNhaXuatBan.NXB_DUOCCHON;
        return new SachCT(null, namXB, icon, giaNhapChuan, nxb, sach);
    }
    
    private List<TheLoaiSach> getListTheLoai(){
        List<JCheckBox> _lst = new ArrayList<>();
        List<TheLoaiSach> _lstTLS = new ArrayList<>();
        for (int j = 0; j < boxTheLoai.getComponentCount(); j++) {
            if(j+1==boxTheLoai.getComponentCount()){
                break;
            }
            _lst.add((JCheckBox) boxTheLoai.getComponent(j+1));
        }
        for (JCheckBox jCheckBox : _lst) {
            if(jCheckBox.isSelected()){
                String ten = jCheckBox.getText();
                TheLoaiSach tls = SERVICE_TLS.getByName(ten);
                _lstTLS.add(tls);
            }
        }
        return _lstTLS;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel Btn;
    private javax.swing.JPanel PnThongTinSach;
    public static javax.swing.JPanel boxTheLoai;
    private javax.swing.JLabel btnDong;
    private javax.swing.JButton btnHoanThanh;
    private javax.swing.JButton btnLayThongTin;
    private javax.swing.JButton btnNXB;
    private javax.swing.JButton btnNhaCungCap;
    private javax.swing.JButton btnTacGia;
    private javax.swing.JButton btnTaiAnh;
    public static javax.swing.JButton btnTheLoai;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JComboBox<String> cbxNCC;
    public static javax.swing.JComboBox<String> cbxNhaXuatBan;
    private javax.swing.JLabel imgAnhSach;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblTacGia;
    private javax.swing.JLabel lblToday;
    private javax.swing.JRadioButton rdoChuaCo;
    private javax.swing.JRadioButton rdoDaCo;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaSach;
    private javax.swing.JTextField txtNamXuatBan;
    private javax.swing.JTextField txtSoLuongNhap;
    private javax.swing.JTextField txtTenSach;
    // End of variables declaration//GEN-END:variables
}
